id: I0F820187
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T22:45:32+00:00'
last_modified: '2022-06-15T18:48:01.869754+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W27311
  title: བོད་ཀྱི་ཆོས་སྲིད་ཟུང་འབྲེལ་སྐོར་བཤད་པ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '9594':
      image_group_id: I4312
      title: ''
      total_pages: 166
      order: 1
      base_file: 9594.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
